# Test all for Castellani Davide
name: Create md

on: push

jobs:
  create-md:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt install moreutils -y
        ls -d * -1 | ts - > README.md
        cat README.md
