# Test all for Castellani Davide
name: Create md

on: push

jobs:
  create-md:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Create file
      run: |
        python3 << EOF
        import os
        file_content = '# Lavori di Castellani Davide :octocat:\n![](https://www.castellanidavide.it/assets/img/main-covers/main.jpg)\n'

        for i in sorted([x for x in os.listdir('./') if not x[0] == '.' and os.path.isdir(x)]): file_content += f' - [{i}](https://github.com/CastellaniDavideTest/Test22-2020-2022-T-CI/blob/18576/{i}/docs/README.md)\n'
        
        file_contents = '\n---\nMade by Castellani Davide \nIf you have any problem please contact me:\n - help@castellanidavide.it\n'
        open('README.md', 'w+').write(file_content)                          
        EOF
        cat README.md
    - name: Upload file
      run: |
        git config --global user.name 'DavideC03'
        git config --global user.email 'help@castellanidavide.it'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git checkout "${GITHUB_REF:11}"
        git commit -am "Update README.md"
        git push
