# Test all for Castellani Davide
name: Create md

on: push

jobs:
  create-md:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Create file
      run: |
        python3 << EOF
        import os
        file_content = '# Lavori di Castellani Davide\n'

        for i in [x for x in os.listdir('./') if not x[0] == '.']: file_content += ' - [i](f'https://github.com/CastellaniDavideTest/Test22-2020-2022-T-CI/blob/18576/{i}/docs/README.md')
        open('README.md', 'w+').write(file_content)                          
        EOF
        cat README.md
