# Test all for Castellani Davide
name: Create md

on: push

jobs:
  create-md:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Create file
      run: |
        python3 -c "import os;content = '';for folder in [x for x in os.listdir('./') if not x[0] == '.'] : content += ' - ' + folder;open('README.md', 'w+').write(content)"
        cat README.md
